//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversor de número a texto en gallego..
        /// </summary>
        internal static string InicioCabecera {
            get {
                return ResourceManager.GetString("InicioCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede que el número o la parte decimal sea demasiado grande..
        /// </summary>
        internal static string listaError1 {
            get {
                return ResourceManager.GetString("listaError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO escriba el número con letras.
        /// </summary>
        internal static string listaError2 {
            get {
                return ResourceManager.GetString("listaError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba un número sin coma ni punto para los miles o millones:    13289      53625999567.
        /// </summary>
        internal static string listaError3 {
            get {
                return ResourceManager.GetString("listaError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los miles o millones se pueden separar con un espacio en blanco:    13 289      53 625 999 567.
        /// </summary>
        internal static string listaError4 {
            get {
                return ResourceManager.GetString("listaError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los miles o millones se pueden separar con un punto:    13.289      53.625.999.567.
        /// </summary>
        internal static string listaError5 {
            get {
                return ResourceManager.GetString("listaError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para escribir fracciones use la barra:    3/4    78/125    30/452    123/125.
        /// </summary>
        internal static string listaError6 {
            get {
                return ResourceManager.GetString("listaError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para escribir decimales use la coma:    3,4    78,125    30,452    123,125.
        /// </summary>
        internal static string listaError7 {
            get {
                return ResourceManager.GetString("listaError7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba un número con cifras.
        /// </summary>
        internal static string placeholder {
            get {
                return ResourceManager.GetString("placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se puede convertir números a letras en cardinal, números en letras ordinal,números en letras decimal, números en letras fraccionario o partitivo y multiplicativo. Se ofrece información morfológica, ortográfica y gramatical de cada uno de los números convertidos a letras. Además, se incluyen ejemplos que ayudan a la comprensión y buen uso..
        /// </summary>
        internal static string textoInicial1 {
            get {
                return ResourceManager.GetString("textoInicial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba un número sin coma ni punto para los miles o millones. Los miles o millones se pueden separar con un espacio en blanco. En los decimales use la coma &quot;,&quot;. Para escribir fracciones use la barra inclinada &quot;/&quot;..
        /// </summary>
        internal static string textoInicial2 {
            get {
                return ResourceManager.GetString("textoInicial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba los ejemplos.
        /// </summary>
        internal static string titEjemplos {
            get {
                return ResourceManager.GetString("titEjemplos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los formatos admitidos para el gallego son los siguientes:.
        /// </summary>
        internal static string titError {
            get {
                return ResourceManager.GetString("titError", resourceCulture);
            }
        }
    }
}
