//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjetivo.
        /// </summary>
        internal static string Adjetivo {
            get {
                return ResourceManager.GetString("Adjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cardinal.
        /// </summary>
        internal static string Cardinal {
            get {
                return ResourceManager.GetString("Cardinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal.
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión con adjetivo.
        /// </summary>
        internal static string Expresión_con_adjetivo {
            get {
                return ResourceManager.GetString("Expresión con adjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión con verbo.
        /// </summary>
        internal static string Expresión_con_verbo {
            get {
                return ResourceManager.GetString("Expresión con verbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fraccionario.
        /// </summary>
        internal static string Fraccionario {
            get {
                return ResourceManager.GetString("Fraccionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplicativo.
        /// </summary>
        internal static string Multiplicativo {
            get {
                return ResourceManager.GetString("Multiplicativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cento, millón, billón, trillón, aunque expresan número, funcionan como sustantivos, igual que ducia, decena, centena..
        /// </summary>
        internal static string NotaCardinal1 {
            get {
                return ResourceManager.GetString("NotaCardinal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las antiguas formas duzentos y trezentos en el lenguaje moderno han sido reemplazadas por las más transparentes douscentos y trescentos..
        /// </summary>
        internal static string NotaCardinal2 {
            get {
                return ResourceManager.GetString("NotaCardinal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo admiten variación de género los cardinales terminados en un, dous y -centos (un/unha, dous/dúas, douscentos/as, trescentos/as, etc.)..
        /// </summary>
        internal static string NotaCardinal3 {
            get {
                return ResourceManager.GetString("NotaCardinal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los números mayores que el cuadrillón no están recogidos en el Diccionario de la RAG.
        /// </summary>
        internal static string NotaCardinal4 {
            get {
                return ResourceManager.GetString("NotaCardinal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuando los cardinales son sustantivos son siempre masculinos, excepto aquellas formas que se refieren a las horas (la una, las dos, ...)..
        /// </summary>
        internal static string NotaCardinal5 {
            get {
                return ResourceManager.GetString("NotaCardinal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A partir de 1/11 (y exceptuados 1/100, 1/1000,1/1.000.000...) el partitivo se hace añadiendo el sufijo -avo al cardinal: (1/16) un dezaseisavo, (2/29) dous vinte e noveavos, (7/345) sete trescentoscorenta e cincoavos..
        /// </summary>
        internal static string NotaFraccionario1 {
            get {
                return ResourceManager.GetString("NotaFraccionario1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas estas formas admiten morfemas de género y número, que en las formas compuestas sólo se adjuntan al último elemento (oitavo, -a)..
        /// </summary>
        internal static string NotaFraccionario2 {
            get {
                return ResourceManager.GetString("NotaFraccionario2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generalmente, los fraccionarios femeninos son adjetivos y los masculinos sustantivos..
        /// </summary>
        internal static string NotaFraccionario3 {
            get {
                return ResourceManager.GetString("NotaFraccionario3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A partir de 11 (y excepto el  100) e forman mediante el cardinal correspondiente seguido de la palabra veces..
        /// </summary>
        internal static string NotaMultiplicativo1 {
            get {
                return ResourceManager.GetString("NotaMultiplicativo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Como sustantivos son siempre masculinos..
        /// </summary>
        internal static string NotaMultiplicativo2 {
            get {
                return ResourceManager.GetString("NotaMultiplicativo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los numeros del 2 al 10, y el 100 tiene forma femenina..
        /// </summary>
        internal static string NotaMultiplicativo3 {
            get {
                return ResourceManager.GetString("NotaMultiplicativo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas estas formas admiten morfemas de género y número, que en las formas compuestas sólo se adjuntan al último elemento (décimo primeira)..
        /// </summary>
        internal static string NotaOrdinal1 {
            get {
                return ResourceManager.GetString("NotaOrdinal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los ordinales 11 y 12 admiten dos variantes undécimo y décimo primero, duodécimo y décimo segundo..
        /// </summary>
        internal static string NotaOrdinal2 {
            get {
                return ResourceManager.GetString("NotaOrdinal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generalmente son adjetivos, y pueden ir antepuestos o pospuestos al sustantivo, siendo más frecuente su aparición por delante..
        /// </summary>
        internal static string NotaOrdinal3 {
            get {
                return ResourceManager.GetString("NotaOrdinal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordinal.
        /// </summary>
        internal static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pronombre.
        /// </summary>
        internal static string Pronombre {
            get {
                return ResourceManager.GetString("Pronombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sintagma nominal.
        /// </summary>
        internal static string Sintagma_nominal {
            get {
                return ResourceManager.GetString("Sintagma nominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo.
        /// </summary>
        internal static string Sustantivo {
            get {
                return ResourceManager.GetString("Sustantivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplos.
        /// </summary>
        internal static string TitEjemplos {
            get {
                return ResourceManager.GetString("TitEjemplos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        internal static string TitNotas {
            get {
                return ResourceManager.GetString("TitNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las opciones y funciones.
        /// </summary>
        internal static string TitOpciones {
            get {
                return ResourceManager.GetString("TitOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo, adjetivo y pronombre.
        /// </summary>
        internal static string TitOpcionesCardinal1 {
            get {
                return ResourceManager.GetString("TitOpcionesCardinal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma femenina.
        /// </summary>
        internal static string TitOpcionesCardinal2 {
            get {
                return ResourceManager.GetString("TitOpcionesCardinal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión.
        /// </summary>
        internal static string TitOpcionesDecimal {
            get {
                return ResourceManager.GetString("TitOpcionesDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo masculino.
        /// </summary>
        internal static string TitOpcionesFraccionario1 {
            get {
                return ResourceManager.GetString("TitOpcionesFraccionario1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjetivo y pronombre femenino.
        /// </summary>
        internal static string TitOpcionesFraccionario2 {
            get {
                return ResourceManager.GetString("TitOpcionesFraccionario2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión con adjetivo.
        /// </summary>
        internal static string TitOpcionesMultiplicativo1 {
            get {
                return ResourceManager.GetString("TitOpcionesMultiplicativo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión con verbo.
        /// </summary>
        internal static string TitOpcionesMultiplicativo2 {
            get {
                return ResourceManager.GetString("TitOpcionesMultiplicativo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo masculino y adjetivo.
        /// </summary>
        internal static string TitOpcionesMultiplicativo3 {
            get {
                return ResourceManager.GetString("TitOpcionesMultiplicativo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verbo.
        /// </summary>
        internal static string TitOpcionesMultiplicativo4 {
            get {
                return ResourceManager.GetString("TitOpcionesMultiplicativo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma femenina.
        /// </summary>
        internal static string TitOpcionesMultiplicativo5 {
            get {
                return ResourceManager.GetString("TitOpcionesMultiplicativo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjetivo y pronombre.
        /// </summary>
        internal static string TitOpcionesOrdinal1 {
            get {
                return ResourceManager.GetString("TitOpcionesOrdinal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma femenina.
        /// </summary>
        internal static string TitOpcionesOrdinal2 {
            get {
                return ResourceManager.GetString("TitOpcionesOrdinal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias.
        /// </summary>
        internal static string TitReferencias {
            get {
                return ResourceManager.GetString("TitReferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verbo.
        /// </summary>
        internal static string Verbo {
            get {
                return ResourceManager.GetString("Verbo", resourceCulture);
            }
        }
    }
}
